title: Nishil Writes
author: Nishil 
email: nishil_443@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Reading and writing my time away. 
  From fiction to tech, I take a whim to anything.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
